### ISSUE TITLE
Handles are difficult to grab on iPad "Flow" scene. Increase size of touch area.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/fluid-pressure-and-flow#188]
Test device: iPad 2
Operating System: iOS 7
Browser: Safari
Problem description: Handles are difficult to grab.

Severity: High 

Troubleshooting information (do not edit):
Name: Fluid Pressure and Flow
URL: http://www.colorado.edu/physics/phet/dev/html/fluid-pressure-and-flow/1.0.0-dev.15/fluid-pressure-and-flow_en.html
Version: 1.0.0-dev.15
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: disabled

**Comment by pixelzoom** [comment]
@samreid should the ready-for-review label be removed?  Not clear what state this issue is in.

**Comment by samreid** [comment]
Let's close this for now, it sounds like it was addressed.  If not, it will be discovered when we resume work on the sim.
