### ISSUE TITLE
Scenery-phet needs a new measuring tape

### ISSUE THREAD

**Issue by samreid** [phetsims/fluid-pressure-and-flow#2]
At my recommendation, the code + image from measuring tape was copied from gravity-and-orbits to this simulation.  A better long term solution would be for the measuring tape code to be moved to scenery-phet so that both simulations can use a single implementation.  I'll assign this issue for me to work on.

**Comment by bereaphysics** [comment]
FPAF is making uses of the Scenery-phet MeasuringTape.Closing.
