### ISSUE TITLE
phetLibs incorrect in package.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fluid-pressure-and-flow#265]
fluid-pressure-and-flow-config.js indicates a dependency on under-pressure, which is not listed in phetLibs in package.json.  This caused me significant grief in phetsims/scenery-phet#139, because I refactored fluid-pressure-and-flow before under-pressure, and was not expecting a sim-to-sim dependency.

**Comment by pixelzoom** [comment]
Fixed, assigning to @samreid so he's aware of this. Feel free to close.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
