### ISSUE TITLE
branch: experimental-webgl-support

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fluid-pressure-and-flow#269]
Please describe.

**Comment by samreid** [comment]
Hackish attempt to use scenery nodes with renderer:webgl to show the particles.  Very immature.

**Comment by zepumph** [comment]
Can this branch be deleted @samreid?

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by samreid** [comment]
Deleted via the GitHub web interface, closing.
