### ISSUE TITLE
icons needed

### ISSUE THREAD

**Issue by jbphet** [phetsims/fluid-pressure-and-flow#286]
The icons currently used in this sim are screen shots and look quite cluttered.  It would be great to have something more clean and eye catching.  Screen shot of current icons below.

![fpaf-home-screen](https://cloud.githubusercontent.com/assets/3082831/13967908/3d5547c8-f03f-11e5-9510-50f2bb5a2600.PNG)

**Comment by zepumph** [comment]
Covered in https://github.com/phetsims/fluid-pressure-and-flow/issues/161
