### ISSUE TITLE
adjust touchArea options for HSlider thumb 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fluid-pressure-and-flow#292]
In https://github.com/phetsims/sun/issues/254, the touchArea defaults for HSlider thumb were changed so that they default to pixels, not a percentage of the thumb size.  Sims that use HSlider's `thumbSize` option will therefore need to also specify `thumbTouchAreaXDilation` and `thumbTouchAreaYDilation`.

**Comment by samreid** [comment]
I reviewed the pointer areas for all slider in FPAF, and they are all a good size and do not overlap other touch areas.
