### ISSUE TITLE
Deprecate PropertySet

### ISSUE THREAD

**Issue by zepumph** [phetsims/fluid-pressure-and-flow#295]
From https://github.com/phetsims/axon/issues/102, this issue is to track progress of PropertySet --> Property conversion in this repo.

I see 15 Usages of `PropertySet.call(` in this repo:
- [x] FluidColorModel
- [x] Hose
- [x] ChamberPoolModel
- [x] Sensor
- [x] FluxMeter
- [x] PoolWithFaucetsMeter
- [x] WaterDrop
- [x] FaucetModel
- [x] UnderPressureModel
- [x] MassModel
- [x] WaterTowerModel
- [x] WaterTower
- [x] PipeControlPoint
- [x] Pipe
- [x] FlowModel

About 80 Properties in total.

My thoughts on process:
1. I am not too familiar with PropertySet, but have spent some time looking into sims that use it.
2. I take a small file and convert it (some file like `Hose.js` that just has two properties)
3. I submit it to @samreid for review.
4. We go from there. I think a pairing session to pick his brain on "best practices" would probably be best.

@samreid please state objections or comments. I think I will potentially try to do step 2 sometime later today.

**Comment by samreid** [comment]
Sounds OK, my tips for success are:
1. do one property at a time (not one property set at a time)

For each one
a. Make sure to use `preventGetSet`
b. Search for all usages of the dynamic property
c. Run a fuzz test to catch any you missed

Happy to meet when our times match up.

**Comment by zepumph** [comment]
Thanks! (And sorry for not assigning you when I wanted feedback)

**Comment by zepumph** [comment]
@samreid how does that look. I converted Hose.js from PropertySet. I ended up still using Events  as the parent, which is deprecated, but I guess that's another job for this repo at some time (converting to emitters).

Also take your time. I won't be looking at this until at least Sept 14th.

**Comment by samreid** [comment]
I added 
```js
    Property.preventGetSet( this, 'angle' );
    Property.preventGetSet( this, 'height' );
```
and didn't see any issues during fuzz testing.  Everything looks good.  The only thing I would recommend to do differently is to leave in `preventGetSet` calls until everything is complete (in case different code gets exercised in a later use case), then we can remove them as a batch later on.

**Comment by samreid** [comment]
I've been tracking some of my commits for this over in https://github.com/phetsims/axon/issues/102

**Comment by samreid** [comment]
I finished this issue in the axon issue, closing.
