### ISSUE TITLE
Replace Events with Emitter

### ISSUE THREAD

**Issue by zepumph** [phetsims/fluid-pressure-and-flow#297]
From https://github.com/phetsims/axon/issues/142, these occurences of `Events` should be replaced with emitter. 

It looks like there are three files that import `Events`:

- [x] `Sensor.js`
- [x] `Hose.js`
- [x] `FluxMeter.js`

**Comment by zepumph** [comment]
@samreid will you please review the conversion commits above?

**Comment by samreid** [comment]
Change sets look great, thanks!
