### ISSUE TITLE
Does under-pressure need to be a phetLib?

### ISSUE THREAD

**Issue by zepumph** [phetsims/fluid-pressure-and-flow#303]
In the `package.json` I see:
```js
    "phetLibs": [
      "under-pressure"
    ],
```

Is this necessary? I thought that the under-pressure sim uses code that lives in FPAF, not the other way around. @jonathanolson does this seem right to you?

**Comment by pixelzoom** [comment]
This dependency is vestigial and should be removed. user-pressure code was migrated to fluid-pressure-and-flow in #266.

**Comment by pixelzoom** [comment]
Dependency was remove in the above commit. Tested by doing a build, then running the built version.  Closing.
