### ISSUE TITLE
Water tower velocity sensor is not working

### ISSUE THREAD

**Issue by ayrimsal** [phetsims/fluid-pressure-and-flow#313]
The velocity sensor in water tower screen is not working, does not measure at all. Also units panel, velocity, and pressure sensors are not displayed in the panel on the upper right corner panel, instead velocity and units are displayed next to the water tower, and pressure sensor is displayed at the bottom of the water tower.
Finally the default index_en.html file is not working.

**Comment by ariel-phet** [comment]
@ayrimsal you are correct on all accounts. This sim is still in development and not yet published, so many features are broken or not yet complete.

Closing
