### ISSUE TITLE
Jupiter gravity is incorrect

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fluid-pressure-and-flow#315]
@ariel-phet the value used in the published version of Under Pressure is 24.9 m/s<sup>2</sup>. This differs from M&S (and the correct value according to google) which uses 24.79 m/s<sup>2</sup>, rounded to 24.8 m/s<sup>2</sup> in the slider readout of M&S.

It would be nice to change the value used in UP to 24.79 m/s<sup>2</sup>, unless there is some other reason 24.9 m/s<sup>2</sup> was chosen. Assigning to @ariel-phet just to let him know, and this would probably be a one line change if the sim's code is written well.

**Comment by ariel-phet** [comment]
@phet-steele how did you notice this...I have to ask...

**Comment by phet-steele** [comment]
> how did you notice this...I have to ask...

Like, how do I know the value the sim is using? I looked at https://github.com/phetsims/fluid-pressure-and-flow/blob/master/js/common/Constants.js#L20

**Comment by ariel-phet** [comment]
@phet-steele no more, why did you think to compare...did some part of your detail oriented brain decide "hey I think this was different in another sim"? And did you check pendulum lab and such?

**Comment by ariel-phet** [comment]
@chrisklus as @phet-steele mentioned, this should be a very easy change. Under pressure would also probably be a nice sim to republish and get on chipper 2.0. 

Looks like there are one or two open issues for under pressure, but lets see if this one is easy to fix. Not a high priority.

**Comment by phet-steele** [comment]
> did some part of your detail oriented brain decide "hey I think this was different in another sim"? And did you check pendulum lab and such?

Yes and yes, PL is 24.79 m/s<sup>2</sup>.

**Comment by chrisklus** [comment]
Nice catch @phet-steele! I changed the constant to two decimal places and the sim rounds it to 1 at 24.8, just like it does for Mars.
