### ISSUE TITLE
There are translations for this sim, and it hasn't be published.  What should we do?

### ISSUE THREAD

**Issue by jbphet** [phetsims/fluid-pressure-and-flow#337]
@liam-mulhall was working on https://github.com/phetsims/website/issues/1362, and he discovered that there were quite a number of translations for this sim, yet to my knowledge, it has never been published.  Have a look at https://github.com/phetsims/babel/tree/master/fluid-pressure-and-flow to see the list of translated string files.

So, a couple of question arise:

Does anyone know how this might have happened?  Was this sim published as a prototype or something?

Should these be deleted, or should we keep them around for when the sim is published?  It will be a bit of an issue if any strings change or are added, because we will end up with a bunch of partial translations if these are kept.

Assigning to the responsible dev for this repo.

**Comment by jbphet** [comment]
Okay, I think I've solved the mystery here.  The under-pressure sim _is_ published, and it is a subset of fluid-pressure-and-flow, so many of its strings for under-pressure are stored in the fluid-pressure-and-flow repo.  The translations that we're seeing here have been for under-pressure, which is fine.  We've just never run into a case where a subset sim has been published for years without the full sim ever going live, so it threw us.

I just looked through the translation files in the under-pressure sim, and something is a bit odd about some of them.  There is more in some of them than I would expect.  I'll log a separate issue to follow up on that when and if fluid-pressure-and-flow is published, but will mark is as deferred since I don't think it is pressing.

So, in the end, this is a non-problem.  I'd like @zepumph and @liam-mulhall to read through this so that we are all clear on it, at which point this can be closed.

- [ ] @zepumph 
- [ ] @liam-mulhall 

Last one out please turn off the lights.

**Comment by liam-mulhall** [comment]
For some reason, I am unable to edit your comment @jbphet. I think this might have to do with my GitHub team settings? Not sure. In any case, I've read through the issue and I'm happy to close it.
